### PR TITLE
Improvements to the UI and documentation

### PR DESCRIPTION
**Pull request by edemiguel**
There are a few changes that where usefull to me and I'd like to share.
- Output last modification date per file
- Listing current folder files after uploading o deleting
- New "go to parent folder" icon in search results
- Fixing the Usage instructions

### CODE REVIEW

**Comment by kristian** [comment]
Hey, some very good changes, thanks for the contribution! 👍 

Some questions before I pull the request:

- I like to "goto parent folder" feature for the search. Would you agree to switch to the &#128449; icon instead of the one you are currently using, to not break the "black & white" UI?
- Second in your bb1e88c commit, you added a catch for NoClassDefFoundError. I don't get it, why should this be thrown? Roots is a local class, which should always be available.
- Last but not least: What is the reasoning behind adding the runtime path to the UI? I don't really like to expose this generally, because your local explorer doesn't show such information either. I don't think it will be useful for a lot of people using the servlet. Mind to remove it before the pull?

Thanks & best regards, Kristian

**Comment by edemiguel** [comment]
Ok, thanks for asking:
- In chrome you can see the "goto parent folder" in black and white, may be you're using firefox. I'll change it but I think you'll need to use a more descriptive solution.
- In our weblogic server, it can't find the root folders and I had a NoClassDefFoundError that I tried to catch to know more about the problem.

> java.lang.NoClassDefFoundError: Could not initialize class javax.swing.filechooser.UnixFileSystemView
> 	at javax.swing.filechooser.FileSystemView.getFileSystemView(FileSystemView.java:86)
> 	at lc.kra.servlet.FileManagerServlet$Roots.<clinit>(FileManagerServlet.java:199)
> 	at lc.kra.servlet.FileManagerServlet.service(FileManagerServlet.java:80)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)
> 	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
> 	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
> 	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
> 	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
> 	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
> 	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
> 	at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:115)
> 	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:77)
> 	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
> 	at org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)
> 	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
> 	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
> 	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
> 	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3451)
> 	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3417)
> 	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
> 	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
> 	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
> 	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280)
> 	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196)
> 	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)
> 	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632)
> 	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256)
> 	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
> 	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)

The problem is in this line:

`private static final FileSystemView fileSystemView = FileSystemView.getFileSystemView();`

You use the `FileSystemView` to display the folder as it would be displayed in a system file browser. I think you shuouldn't use it.

- I used the "Runtime application path" to find my web server installation and get some log files that we needed.  I can delete it.

Anything else?

**Comment by kristian** [comment]
@edemiguel, again thanks for your contribution!

I got you with the class exception. I see that some JREs may not provide a implementation for that class. But I would move it into the Roots class, so a "root" is displayed in any case (even if the display name may not be available).

I have "cherry picked" both of your suggestions and merged it into version 0.1.1 of the servlet! Thanks!

**Comment by edemiguel** [comment]
One more thing!
I was thinking of adding a delete button. Do you think it's a good idea?
I allso thought about how usefull this could be with a log viewer. What do you think?

**Comment by kristian** [comment]
Hello.

Adding a delete button is no big deal, but I was struggling when I originally made the FileManagerServlet... the servlet has no "modification" option (except upload). If I would add "delete" why not rename, move, copy, etc. Also "delete" could be VERY dangerous. Therefore I decided to not at it by default.

Also with having a "log viewer". I think it is a great idea, but adding a file viewer into the servlet is more or less a bottomless pit... you will have to add support for so many file types, because everyone will say, hey my logs are in XML, mine are in whatever kind of format, so you will have to see how to parse / display it well. Simply sending it to the browser in "plain text" is not sufficient for most of the files unfortunately.

Thanks for your suggestions. In case you would like to go a little more into detail of one of the two items. But I think they are larger development tasks and I unfortunately have not so much time at the moment to implement such a feature...

Thanks & best regards,
Kristian

**Comment by edemiguel** [comment]
Hello again!

What I meant is that I would like to do it in the future, and then if you agree, add them to your repository.

Regards
Enrique

**Comment by kristian** [comment]
Sure! I am always open to accept pull requests, if they are valuable to everyone. So the feature should not be too specific (like e.g. displaying the JRE path), but improvements fitting the theme, yes definitely I will pull! :)

**Pull request closed without merging**
